# -*- coding: utf-8 -*-
"""practice json

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ux8Ar3YmyDifEMVWCqh8bjNWxZeojMvm
"""

import json

travel_data = {
    "cities": {
        "chennai": {
            "places": ["Marina Beach", "Kapaleeshwarar Temple", "Fort St. George"],
            "food": ["Idli", "Dosa", "Filter Coffee"],
            "best_time": "November to February",
            "budget_per_day": 2000
        },
        "bangalore": {
            "places": ["Lalbagh", "Cubbon Park", "Bangalore Palace"],
            "food": ["Bisi Bele Bath", "Vada", "Filter Coffee"],
            "best_time": "October to February",
             "budget_per_day": 5000
        },
        "delhi": {
            "places": ["Red Fort", "India Gate", "Qutub Minar"],
            "food": ["Chole Bhature", "Paratha", "Butter Chicken"],
            "best_time": "October to March",
             "budget_per_day": 3000
        },
        "mumbai": {
            "places": ["Gateway of India", "Marine Drive", "Elephanta Caves"],
            "food": ["Vada Pav", "Pav Bhaji", "Bhel Puri"],
            "best_time": "November to February",
             "budget_per_day": 4000
        }
    }
}

with open("travel.json", "w") as f:
    json.dump(travel_data, f, indent=4)

print("✅ travel.json created")


import json

with open("travel.json", "r") as file:
    data = json.load(file)

print("🌍 TRAVEL GUIDE CHATBOT")
print("Type a city name (or 'exit' to stop)\n")

while True:
    city = input("You: ").lower()

    if city == "exit":
        print("Chatbot: Happy travelling ✈️")
        break

    if city in data["cities"]:
        info = data["cities"][city]

        print("\n📍 Places to Visit:")
        for place in info["places"]:
            print("-", place)

        print("\n🍽 Famous Food:")
        for food in info["food"]:
            print("-", food)

        print("\n🕒 Best Time to Visit:")
        print(info["best_time"])

        # 💰 Budget estimation
        days = int(input("\n📅 How many days are you planning? "))
        total_budget = days * info["budget_per_day"]

        print(f"💰 Estimated Budget for {days} days: ₹{total_budget}")
        print("-" * 30)

    else:
        print("Chatbot: Sorry, city not found 😕")

!pip install -q -U google-generativeai

import google.generativeai as genai
API_KEY = "AIzaSyCG7RF1Dc2fnOPY-ipssaD3DUb5iFO5QBY"
genai.configure(api_key=API_KEY)

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    system_instruction=(
        "You are a travel chatbot. For any city provided, give: "
        "1. A list of 3-4 Places to Visit. "
        "2. A list of 3-4 famous Foods. "
        "3. The Best Time to visit. "
        "4. Budget per day (INR): <number only>"
        "5. Hotel cost per day (INR): <number only>"
    )
)

print("🌍 AI TRAVEL GUIDE CHATBOT")
print("I can tell you about ANY city in the world!")
print("Type a city name (or 'exit' to stop)\n")

while True:
    city_input = input("You: ").strip()

    if city_input.lower() == "exit":
        print("Chatbot: Happy travelling ✈️")
        break

    try:

        prompt = f"Give me travel details for {city_input}. Please include the budget_per_day as a single number at the end."
        response = model.generate_content(prompt)

        print("\n--- Travel Recommendations ---")
        print(response.text)

        days = input("\n📅 How many days are you planning? (Enter a number or press Enter to skip): ")
        if days.isdigit():
            print(f"Chatbot: Great! Have a wonderful {days}-day trip to {city_input}!")

        print("-" * 30)

    except Exception as e:
        print(f"Chatbot: Oops! Something went wrong. Check your API key or connection. \nError: {e}")

"""NEW CODE"""

import google.generativeai as genai
import re

API_KEY = "AIzaSyCG7RF1Dc2fnOPY-ipssaD3DUb5iFO5QBY"
genai.configure(api_key=API_KEY)

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    system_instruction=(
        "You are a travel chatbot. For any city provided, give: "
        "1. A list of 3-4 Places to Visit. "
        "2. A list of 3 famous Foods. "
        "3. The Best Time to visit. "
        "4. Hotel cost per day (INR): <number only> - provide this as a clear number"
        "Format your response clearly with labeled sections."
        "5.I want a day by day plan of what all to visit in that place "
    )
)

print("🌍 AI TRAVEL GUIDE CHATBOT")
print("I can tell you about ANY city in the world!")
print("Type a city name (or 'exit' to stop)\n")

greetings = ['hi', 'hello', 'hey', 'greetings', 'good morning', 'good afternoon', 'good evening']

while True:
    city_input = input("Enter city or place: ").strip()

    if city_input.lower() == "exit":
        print("Happy travelling ✈️")
        break

    if city_input.lower() in greetings:
        print("Chatbot: Hello! 👋 Welcome to the AI Travel Guide! Which city would you like to explore today?\n")
        continue

    try:
        prompt = f"Give me travel details for {city_input}. Include hotel cost per day in INR as a number."
        response = model.generate_content(prompt)

        print("\n--- Travel Recommendations ---")
        print(response.text)
        print("-" * 30)

        hotel_cost_match = re.search(r'Hotel cost per day[:\s]+(?:INR[:\s]+)?(\d+)', response.text, re.IGNORECASE)
        hotel_cost_per_day = int(hotel_cost_match.group(1)) if hotel_cost_match else None

        total_days = input("\n📅 How many total days will you stay in this place? ")
        if not total_days.isdigit():
            print("Invalid input. Skipping cost calculation.\n")
            continue
        total_days = int(total_days)

        hotel_days = input("🏨 How many days will you stay in a hotel? ")
        if not hotel_days.isdigit():
            print("Invalid input. Skipping cost calculation.\n")
            continue
        hotel_days = int(hotel_days)

        if hotel_days > total_days:
            print("⚠️ Hotel days cannot exceed total days. Please try again.\n")
            continue

        if hotel_cost_per_day:
            total_hotel_cost = hotel_cost_per_day * hotel_days

            print(f"\n💰 --- COST BREAKDOWN ---")
            print(f"Hotel cost per day: ₹{hotel_cost_per_day}")
            print(f"Hotel days: {hotel_days}")
            print(f"Total hotel cost: ₹{total_hotel_cost}")
            print(f"\n🎒 Total trip duration: {total_days} days")
            print(f"Have a wonderful trip to {city_input}! ✈️")
            print("-" * 30 + "\n")
        else:
            print("⚠️ Could not extract hotel cost. Please try again.\n")

    except Exception as e:
        print(f"Oops! Something went wrong. Check your API key or connection. \nError: {e}\n")

"""NEW-2"""

import google.generativeai as genai
import json
import re

API_KEY = "AIzaSyCG7RF1Dc2fnOPY-ipssaD3DUb5iFO5QBY"
genai.configure(api_key=API_KEY)

model = genai.GenerativeModel(
    model_name="gemini-2.5-flash",
    system_instruction=(
        "You are a travel cost assistant.\n"
        "For any PLACE or CITY, respond ONLY in valid JSON.\n"
        "1. A list of 3-4 Places to Visit. "
        "2. A list of 3 famous Foods. "
        "3. The Best Time to visit."
        "Format:\n"
        "{\n"
        "  \"hotel_cost_per_day\": <number>\n"
        "}\n"

    )
)

print("🌍 AI TRAVEL COST CHATBOT")
print("Chatbot: Hi 👋 How are you?")
print("Chatbot: Please enter a city or place name 😊")
print("Type 'exit' to stop\n")

greetings = ['hi', 'hello', 'hey', 'hii', 'hai', 'good morning', 'good evening', 'good afternoon']

while True:
    user_input = input("You: ").strip()

    if user_input.lower() == "exit":
        print("Chatbot: Happy travelling ✈️")
        break

    # Normalize input for greeting detection
    clean_input = re.sub(r'[^\w\s]', '', user_input.lower()).strip()

    # Greeting handling
    if clean_input in greetings:
        print("Chatbot: Hello! 😊 Please enter a city or place name.\n")
        continue

    # Skip empty input
    if not user_input:
        print("Chatbot: Please enter a valid city or place name.\n")
        continue

    try:
        # 🔹 Call Gemini
        response = model.generate_content(
            f"Give hotel cost details for {user_input}"
        )

        # 🔹 Clean response (remove markdown code blocks if present)
        response_text = response.text.strip()
        if response_text.startswith("```json"):
            response_text = response_text.replace("```json", "").replace("```", "").strip()
        elif response_text.startswith("```"):
            response_text = response_text.replace("```", "").strip()

        # 🔹 Parse JSON safely
        data = json.loads(response_text)
        hotel_cost_per_day = data["hotel_cost_per_day"]

        print(f"\n🏨 Hotel cost per day: ₹{hotel_cost_per_day}")

        # Ask days
        total_days = input("\n📅 Total days staying in the place: ").strip()
        hotel_days = input("🏨 Total days staying in hotel: ").strip()

        if not (total_days.isdigit() and hotel_days.isdigit()):
            print("⚠️ Please enter valid numbers.\n")
            continue

        total_days = int(total_days)
        hotel_days = int(hotel_days)

        if hotel_days > total_days:
            print("⚠️ Hotel days cannot exceed total trip days.\n")
            continue

        if total_days <= 0 or hotel_days <= 0:
            print("⚠️ Days must be greater than 0.\n")
            continue

        # Cost calculation
        total_hotel_cost = hotel_cost_per_day * hotel_days

        print("\n💰 COST SUMMARY")
        print(f"Hotel cost per day : ₹{hotel_cost_per_day}")
        print(f"Hotel days         : {hotel_days}")
        print(f"Total hotel cost   : ₹{total_hotel_cost}")
        print(f"Trip duration      : {total_days} days")
        print(f"Have a wonderful trip to {user_input}! ✈️")
        print("-" * 40 + "\n")

    except json.JSONDecodeError:
        print("⚠️ AI response was not valid JSON. Please try again.\n")
        print(f"Debug - Response received: {response.text[:100]}...\n")
    except KeyError:
        print("⚠️ Could not find hotel cost in response. Please try again.\n")
    except Exception as e:
        print(f"❌ Error: {e}\n")